terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
    }
  }
}

resource "null_resource" "web_content" {
  triggers = {
    always_run = "${timestamp()}"  # This makes it run on every apply
  }

  connection {
    type        = "ssh"
    user        = "ubuntu"
    private_key = file("~/.ssh/id_ed25519")
    host        = aws_instance.unifor_ubuntu[0].public_ip
  }

  provisioner "remote-exec" {
    inline = [
      "echo 'server { listen 80; server_name localhost; location / { root /var/www/html; index index.html; } }' | sudo tee /etc/nginx/sites-available/default",
      <<-EOT
      cat <<'EOF' | sudo tee /var/www/html/index.html
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Welcome to My AWS Server</title>
          <style>
              body {
                  font-family: Arial, sans-serif;
                  line-height: 1.6;
                  margin: 0;
                  padding: 20px;
                  background-color: #f0f2f5;
              }
              .container {
                  max-width: 800px;
                  margin: 0 auto;
                  background-color: white;
                  padding: 20px;
                  border-radius: 8px;
                  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
              }
              h1 {
                  color: #1a73e8;
                  text-align: center;
              }
              .info-section {
                  margin-top: 20px;
                  padding: 15px;
                  background-color: #f8f9fa;
                  border-radius: 4px;
              }
              .server-time {
                  text-align: center;
                  color: #666;
                  font-style: italic;
              }
          </style>
      </head>
      <body>
          <div class="container">
              <h1>Welcome to My AWS EC2 Instance</h1>
              <div class="info-section">
                  <h2>Equipe</h2>
                  <ul>
                      <li>Francisco Artur Cavalcante Neto -- 2417046</li>
                      <li>Felipe Neres Ribeiro -- 2327959</li>
                      <li>João Victor de Andrade Mesquita -- 2416898</li>
                  </ul>
              </div>
              <div class="info-section">
                  <h2>Server Information</h2>
                  <ul>
                      <li>Server: Nginx on Ubuntu</li>
                      <li>Instance Type: t2.micro</li>
                      <li>Region: us-east-1</li>
                  </ul>
              </div>
              <div class="info-section">
                  <h2>About This Page</h2>
                  <p>This page is served by an AWS EC2 instance provisioned using Terraform. 
                     The server is running Nginx and was automatically configured during the instance launch.</p>
              </div>
              <p class="server-time">Page generated by Terraform deployment</p>
          </div>
      </body>
      </html>
      EOF
      EOT
      ,
      "sudo systemctl restart nginx"
    ]
  }
}